{
 "title": "IoT-LoraWAN",
 "description": "Dashboard principale per il progetto Iot-LoraWAN",
 "time": { "from": "2024-11-13T17:47:06.674Z", "to": "2024-11-13T22:32:59.615Z" },
 "templating": {
  "list": [
   {
    "name": "institute",
    "label": "Institute",
    "query": {
     "query": "from(bucket: \"home\")\n  |> range(start: -70d)\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\n  |> distinct(column: \"institute\")\n  |> keep(columns: [\"institute\"])\n"
    }
   },
   {
    "name": "classroom",
    "label": "Classroom",
    "query": {
     "query": "from(bucket: \"home\")\n  |> range(start: -70d)\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\n  |> filter(fn: (r) => r.institute == \"${institute}\")\n  |> distinct(column: \"classroom\")\n  |> keep(columns: [\"classroom\"])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature represents the current air temperature measured in degrees Celsius",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -70d)\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> filter(fn: (r) => r.institute == \"${institute}\")\n  |> filter(fn: (r) => r[\"classroom\"] =~ /^${classroom:regex}$/ )"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity indicates the percentage of moisture present in the air",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -70d)\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> filter(fn: (r) => r.institute == \"${institute}\")\n  |> filter(fn: (r) => r[\"classroom\"] =~ /^${classroom:regex}$/ )"
    }
   ]
  },
  {
   "title": "Correlation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"correlation_data\")\n  |> filter(fn: (r) => r.DevEui == \"${DevEui}\")\n\n"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "\"CO2 denotes the concentration of carbon dioxide in the air, measured in parts per million (ppm), which is important for air quality",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -70d)\n  |> filter(fn: (r) => r._measurement == \"sensor_data\")\n  |> filter(fn: (r) => r._field == \"co2\")\n  |> filter(fn: (r) => r.institute == \"${institute}\")\n  |> filter(fn: (r) => r[\"classroom\"] =~ /^${classroom:regex}$/ )"
    }
   ]
  }
 ]
}