services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper1
    environment: &zookeeper-environment
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-net
      - shared-net

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper2
    environment: *zookeeper-environment
    ports:
      - 32181:3181
    networks:
      - kafka-net
      - shared-net
  
  kafka1:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka1
    depends_on:
      - zookeeper1
      - zookeeper2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:3181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
      - shared-net
  
  kafka2:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka2
    depends_on:
      - zookeeper1
      - zookeeper2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:3181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
      - shared-net

networks:
  kafka-net:
    driver: bridge
  shared-net:
    external: true