services:
  
  spark-master:
    image: bitnami/spark:3.5.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
    networks:
        - shared-net
    volumes:
      - ../../environment:/opt/bitnami/environment
      - ../../data:/opt/bitnami/iot-lorawan
    command: ["/bin/bash", "-c", "pip install -r /opt/bitnami/environment/spark-requirements.txt && /opt/bitnami/scripts/spark/run.sh"]
  
  spark-worker1:
    image: bitnami/spark:3.5.3
    container_name: spark-worker1
    environment: &worker-environment
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - shared-net
    volumes:
      - ../../environment:/opt/bitnami/environment
      - ../../data:/opt/bitnami/iot-lorawan
    command: ["/bin/bash", "-c", "pip install -r /opt/bitnami/environment/spark-requirements.txt && /opt/bitnami/scripts/spark/run.sh"]
    depends_on:
      - spark-master
  
  spark-worker2:
    image: bitnami/spark:3.5.3
    container_name: spark-worker2
    environment: *worker-environment
    networks:
      - shared-net
    volumes:
      - ../../environment:/opt/bitnami/environment
      - ../../data:/opt/bitnami/iot-lorawan
    command: ["/bin/bash", "-c", "pip install -r /opt/bitnami/environment/spark-requirements.txt && /opt/bitnami/scripts/spark/run.sh"]
    depends_on:
      - spark-master
      
networks:
  shared-net:
    external: true