services:
  grafana:
    image: grafana/grafana:11.2.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - '443:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards 
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - shared-net

volumes:
  grafana-storage: {}

networks:
  shared-net:
    external: true