services:
 
  cassandra1:
    image: 'bitnami/cassandra:5.0.1'
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra-net
      - shared-net
    ports:
      - "7000:7000"
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./schema.cql:/schema.cql
      - cassandra1-data:/bitnami 
    environment: &environment
      CASSANDRA_SEEDS: "cassandra1,cassandra2"    # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: StorageLayer
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 200M
      CASSANDRA_STARTUP_CQL: schema.cql
  
  cassandra2:
    image: 'bitnami/cassandra:5.0.1'
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra-net
      - shared-net
    ports:
      - "7001:7000"
      - "9043:9042"  
    environment: *environment
    volumes:
      - ./schema.cql:/schema.cql
      - cassandra2-data:/bitnami 
  
  cassandra3:
    image: 'bitnami/cassandra:5.0.1'
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra-net
      - shared-net
    ports:
      - "7002:7000"
      - "9044:9042"
    environment: *environment
    volumes:
      - cassandra3-data:/bitnami 

networks:
  cassandra-net:
    driver: bridge
  shared-net:
    external: true

volumes:
  cassandra1-data:
  cassandra2-data:
  cassandra3-data: