services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/admin-token
      DOCKER_INFLUXDB_INIT_ORG: RomaTre 
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - admin-username
      - admin-password
      - admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - shared-net

secrets:
  admin-username:
    file: admin-username
  admin-password:
    file: admin-password
  admin-token:
    file: admin-token

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  shared-net:
    external: true