CREATE TABLE IF NOT EXISTS stats_by_year_week (
    year INT, 
    week INT, 
    deveui TEXT,
    avg_temperature REAL, 
    max_temperature REAL, 
    min_temperature REAL, 
    stddev_temperature REAL,
    avg_humidity REAL, 
    max_humidity REAL, 
    min_humidity REAL, 
    stddev_humidity REAL,
    avg_co2 REAL, 
    max_co2 REAL, 
    min_co2 REAL, 
    stddev_co2 REAL,
    avg_light_level REAL, 
    max_light_level REAL, 
    min_light_level REAL, 
    stddev_light_level REAL,
    avg_pressure REAL, 
    max_pressure REAL, 
    min_pressure REAL, 
    stddev_pressure REAL,
    avg_tvoc REAL, 
    max_tvoc REAL, 
    min_tvoc REAL, 
    stddev_tvoc REAL,
    PRIMARY KEY (year, week)
);

CREATE TABLE IF NOT EXISTS stats_by_class_year_week (
    classroom TEXT, 
    institute TEXT, 
    deveui TEXT, 
    year INT, 
    week INT,
    avg_temperature REAL, 
    max_temperature REAL, 
    min_temperature REAL, 
    stddev_temperature REAL,
    avg_humidity REAL, 
    max_humidity REAL, 
    min_humidity REAL, 
    stddev_humidity REAL,
    avg_co2 REAL, 
    max_co2 REAL, 
    min_co2 REAL, 
    stddev_co2 REAL,
    avg_light_level REAL, 
    max_light_level REAL, 
    min_light_level REAL, 
    stddev_light_level REAL,
    avg_pressure REAL, 
    max_pressure REAL, 
    min_pressure REAL, 
    stddev_pressure REAL,
    avg_tvoc REAL, 
    max_tvoc REAL, 
    min_tvoc REAL, 
    stddev_tvoc REAL,
    PRIMARY KEY (classroom, institute, year, week)
);


COMMENT ON TABLE stats_by_class_year_week IS 'Statistics computed on sensor data, aggregated by classroom, institute, year, and week.';
COMMENT ON TABLE stats_by_year_week IS 'Statistics computed on sensor data, aggregated by year, and week.';